# Generated by Django 4.1.5 on 2023-06-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
