# Generated by Django 4.1.5 on 2023-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_quantity_remove_product_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
