# Generated by Django 4.1.5 on 2023-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_quantity_product_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profits',
            field=models.FloatField(default=0),
        ),
    ]
