# Generated by Django 4.1.5 on 2023-06-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_profits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profits',
            new_name='profit_amount',
        ),
    ]
